#ifndef SHMINIMAXING_GAME_H
#define SHMINIMAXING_GAME_H

#include <cstdint>
#include <initializer_list>
#include <list>
#include <cassert>
#include <memory>
#include <stack>
#include <vector>

#define DEFAULT_GAME_SELECTION_STATE 0xffff
#define INVALID_PIECE_SELECTION 0x67

namespace quarto
{
    struct bb_wrapper
    {
        uint16_t bb[5];
    };

    void get_sorted_bitboard(std::vector<bb_wrapper>& board_states);
    void add_permutations(std::vector<bb_wrapper>& board_states, unsigned short* game_state, int last_index, int i);
    __uint128_t get_minimized_symmetrical(const std::vector<bb_wrapper>& board_states);
    void get_all_minimized_flips(std::vector<bb_wrapper>& board_states);

    inline bb_wrapper create_wrapper(uint16_t* game_state)
    {
        return bb_wrapper{
            game_state[0],
            game_state[1],
            game_state[2],
            game_state[3],
            game_state[4],
        };
    }

    class game
    {
        uint16_t board_state[5]{0, 0, 0, 0, 0}; // color, size, shape, fill, placed
        uint16_t selection_state = DEFAULT_GAME_SELECTION_STATE;
        uint8_t selected_piece = INVALID_PIECE_SELECTION;
        std::stack<uint16_t> previous_board_states;
        std::stack<uint16_t> previous_selection_states;
        std::stack<uint8_t> previous_selected_pieces;

    public:
        constexpr static int BOARD_COLOR{0};
        constexpr static int BOARD_SIZE{1};
        constexpr static int BOARD_SHAPE{2};
        constexpr static int BOARD_FILL{3};
        constexpr static int BOARD_PLACED{4};

        game() = default;
        game(const uint16_t board_state[], uint16_t selection_state, int selected_piece);
        void do_move(uint8_t square);
        void do_select(uint8_t new_selection);
        void do_select_piece(uint8_t piece);
        void push_state_to_undo_stack();
        void undo();

        [[nodiscard]] bool is_quarto() const;
        [[nodiscard]] bool is_game_over() const;

        void print_state() const;

        [[nodiscard]] std::shared_ptr<game> clone() const
        {
            auto new_game = game(this->board_state, this->selection_state, this->selected_piece);
            return std::make_shared<game>(new_game);
        }

        static constexpr __uint128_t format(const uint16_t* arr)
        {
            __uint128_t ss = 0;

            for (int i = 0; i < 5; ++i)
            {
                ss |= ((static_cast<__uint128_t>(arr[i])) << (16 * i));
            }

            return ss;
        }

        /**
         * @return 1 if our turn -1 if enemy turn
         */
        [[nodiscard]] int move_side() const
        {
            assert(previous_board_states.size() % 2 == 0);

            return ((previous_board_states.size() / 2) % 2 == 0) ? 1 : -1;
        }

        [[nodiscard]] bool can_undo() const
        {
            return !this->previous_board_states.empty();
        }

        [[nodiscard]] __uint128_t canonize() const;

        [[nodiscard]] constexpr uint16_t get_selection_state() const
        {
            return this->selection_state;
        }

        [[nodiscard]] constexpr uint8_t get_selection_piece() const
        {
            return this->selected_piece;
        }

        /**
         * A compute intensive function that computes the best move of the current game object
         *
         * @param time_remaining the time remaning to serach for the best move
         * @return Upper 4 bits are the placement move, lower 4 bits are the selection move
         */
        [[nodiscard]] uint8_t compute_move(int time_remaining) const;

        uint16_t* get_board_state()
        {
            return this->board_state;
        }
    };

    // trust me bro
    static uint16_t QUARTO_MAGIC_VALUES[10] = {
        // DO NOT CHANGE (generated by compute_quarto_magic.py)
        0x8421, 0x1248, 0x8888, 0x4444, 0x2222, 0x1111, 0xf000, 0xf00, 0xf0, 0xf
        // to be really nerdy here optimization could be arranging these in the order of the most common quarto way so like are horizontal quato more common then positive / negative quarto?
    };


    static inline std::vector<uint8_t> QUARTO_PIECES = {
        // DO NOT CHANGE
        0b1111,
        0b0111,
        0b1011,
        0b0011,
        0b1101, // to place
        0b0101,
        0b1001,
        0b0001,
        0b1110,
        0b0110,
        0b1010,
        0b0010,
        0b1100,
        0b0100,
        0b1000,
        0b0000,
    };
} // quarto

#endif //SHMINIMAXING_GAME_H
